<?php

namespace NolarkBundle\Repository;

/**
 * casqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class casqueRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCasqueByType($type) {
        return $this->createQueryBuilder('c')
            ->select('m.nom as marque, c.prix, c.modele, c.classement, c.stock, c.image')
            ->innerJoin('c.marque', 'm')
            ->innerJoin('c.type', 't')
            ->where('t.libelle = :type')->setParameter('type', $type)->getQuery()->getArrayResult();
    }
}
