<?php

namespace NolarkBundle\Repository;

/**
 * casqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class casqueRepository extends \Doctrine\ORM\EntityRepository
{
}
