<?php

namespace NolarkBundle\Repository;

/**
 * typeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getArrayType() {
        return $this->createQueryBuilder('t')->select('t.libelle')->getQuery()->getArrayResult();
    }

}
